# Generated by Django 3.2.16 on 2023-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileforreceiver',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank Account Number', max_length=26),
        ),
    ]
