# Generated by Django 3.2.16 on 2023-01-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followercount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowerCount',
            new_name='FollowersCount',
        ),
    ]
