# Generated by Django 3.2.16 on 2023-01-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='tag',
            field=models.ManyToManyField(blank=True, to='invoices.Tag'),
        ),
    ]
