# Generated by Django 3.2.16 on 2023-01-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hra', '0002_alter_department_dept_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60, unique=True, verbose_name='designation')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'designation',
                'verbose_name_plural': 'designations',
                'db_table': 'designations',
                'ordering': ['designation'],
            },
        ),
    ]
