# Generated by Django 3.2.16 on 2023-01-04 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='category description')),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='category_images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Product')),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_price', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('is_published', models.BooleanField(verbose_name='is product published')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='product_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category', verbose_name='category')),
            ],
        ),
    ]
